version: '3.7'

networks:
  a24-front:
    name: a24-front

services:
  node:
    image: ${HUB}/node:${TAG}
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./.env:/app/.env
    networks:
      - a24-front
    restart: unless-stopped