export default {
    plural: {
        review: ["відгук", "відгука", "відгуків"],
        answers: ["відповідь", "відповіді", "відповідей"],
        days: ["день", "дні", "днів"],
        hours: ["година", "години", "годин"],
        minutes: ["хвилина", "хвилини", "хвилин"],
        seconds: ["секунда", "секунди", "секунд"],
        products: ["товар", "товари", "товарів"],
        coupons: ['купон', 'купона', 'купонів']
    },
    errors: {
        server: {
            default: {
                title: "Ой, щось пішло не так",
                description: "Будь ласка, спробуйте ще раз через 30 секунд"
            }
        }
    },
    calendar: {
        months: ["Січня", "Лютого", "Березня", "Квітня", "Травня", "Червня", "Липня", "Серпня", "Вересня", "Жовтня", "Листопада", "Грудня"]
    },
    review: {
        about: "Відгуки про {0}",
        useful: "Корисний відгук",
        useless: "Некорисний відгук",
        reviewUseful: "Чи є відгук корисним?",
        comment: {
            commentUseful: "Чи є коментар корисним?",
            useful: "Корисний коментар",
            useless: "Некорисний коментар"
        },
        buyersReviews: "Відгуки покупців",
        viewAll: "Дивитися всі відгуки",
        create: "Залишити відгук",
        loginAndCreate: "Увійти та залишити відгук",
        add: "Доповнити сторінку відгуками",
        aboutProduct: "Відгук про товар",
        sendAnswer: "Надіслати відповідь",
        youHaveNotLeftAnyProductReviewsYet: "Ви ще не залишали відгуки про товари",
        createYourFirstOrderToLeaveAReview: "Саме час створити перше замовлення, щоб залишити відгук",
        messages: {
            receivedReview: "Отримали Ваш відгук",
            receivedAnswer: "Отримали Вашу відповідь"
        },
        allReviews: "Всі відгуки",
        firstReviewIsTheMostValuable: "Перший відгук - найцінніший",
        reviewIsTheMostValuable: "Ваш відгук дуже цінний для нас",
        youHaveAlreadyPurchasedThisItem: "Ви вже купували цей товар",
        dontShowMyName: "Не вказувати моє ім'я",
        write: "Написати відгук"
    },
    validation: {
        enterYourRating: "Вкажіть Вашу оцінку",
        enterCorrectPhoneNumber: "Вкажіть коректний номер телефону",
        enterCorrectEmail: "Вкажіть коректну email-адресу",
        mustBeCompleted: "Обов'язково має бути заповнено",
        errorAvatarUpload: "Фото профілю не завантажено. Потрібна картинка в форматі jpeg, png або gif, розміром до 10 МБ.",
        errorUploadUnpackingPhoto: "Неможливо завантажити фото! Завантаження фото заборонена по одній з наступних причин: невірний формат зображення (допустимі формати jpg, png); розмір фото більше необхідного (понад 15 мб); кількість фото перевищує допустимий (10 зображень); фотографія розпізнана як нецензурного характеру."
    },
    oh: "Ой",
    youHaveAlreadyApplied: "Ви вже подавали заявку",
    pageNotFound: "Сторінку не знайдено",
    allAboutProduct: "Все про товар",
    allRoundView: "Круговий огляд для",
    analogs: "Аналоги",
    analogsAndSubstitutes: "Аналоги і замінники",
    analogsAndSubstitutesFor: "Аналоги і замінники для {0}",
    analogsFromOtherVendors: "Аналоги від інших виробників",
    youMayAlsoBeInterestedIn: "Також вас можуть зацікавити",
    seeAllAnalogs: "Дивитися всі аналоги",
    viewAll: "Переглянути все",
    view: "Переглянути",
    all: "Все",
    morkovki: "Морквинки",
    personalAccount: "Особистий кабінет",
    privateData: "Персональні дані",
    personalData: "Персональна інформація",
    productCatalog: "Каталог товарів",
    viewedProducts: "Переглянуті товари",
    attentionToThisItems: "Зверніть увагу",
    bestsellers: "Хіти продажів",
    popularBrands: "Популярні бренди",
    lastReviews: "Останні відгуки",
    usefulArticles: "Корисні статті",
    reviews: "Відгуки",
    vacancies: "Вакансії",
    contacts: "Контакти",
    myReviews: "Мої відгуки",
    myOrders: "Мої замовлення",
    myBonuses: "Мої бонуси",
    bonuses: "Бонуси",
    updateBonuses: "Обновити бонуси",
    amountOfBonusWithoutValue: "Бонусних",
    howToSpendBonuses: "Як витрачати бонуси",
    orderHistory: "Історія замовлення",
    onYourBalance: "На Вашому рахунку",
    wishList: {
        title: "Список бажань",
        emptyList: "Ваш список бажань пустий",
        addProducts: "Додайте до нього товари"
    },
    next: "Далі",
    back: "Назад",
    exit: "Вихід",
    clearlyUnderstood: "Зрозуміло",
    pity: "Шкода",
    hotline: "Гаряча лінія",
    phone: "Телефон",
    toTheNumber: "На номер",
    sentSMSWithCode: "Відправлено SMS з кодом",
    enterCode: "Введіть код",
    enterCodeFromSMSOrViber: "Введіть код перевірки з SMS чи Viber",
    enterSettlementName: "Введіть найменування населеного пункту",
    sendCodeAgain: "Вислати код ще раз",
    availableThrough: "Доступно через",
    userAgreement: {
        title: "Угода користувача",
        acceptTerms: "Продовжуючи, Ви приймаєте умови",
        agreement: "Угоди користувача"
    },
    paymentTypes: {
        cash: "Готівкою",
        cashOnDelivery: "Накладений платіж",
        creditCardOnSite: "Оплата картою на сайті"
    },
    deliveryTypes: {
        courier: "Кур'єр за вашою адресою",
        selfDelivery: "Отримання замовлення в аптеці",
        departmentNovaPoshta: "«Нова Пошта»: до відділення",
        courierFromNovaPoshta: "«Нова Пошта»: за вказаною адресою",
        departmentUkrPoshta: "«Укрпошта»: до відділення",
        courierFromUrkPoshta: "«Укрпошта»: за вказаною адресою",
        departmentJustIn: "«Justin»: до відділення",
        departmentMeest: "«Meest»: доставка у відділення",
        courierFromMeest: "«Meest»: доставка кур'єром",
        departmentiPOST: "iPOST: до відділення",
        courierFromiPOST: "iPOST: доставка кур'єром",
        courierFromUklon: "Uklon: доставка кур'єром",
        withoutDelivery: "Без доставки"
    },
    propertiesOfDrug: "Властивості препарату",
    instructionForUse: "Інструкція для застосування",
    instruction: "Інструкція",
    instructionFromVendor: "Інструкція виробника",
    description: "Опис",
    videoReview: "Відеоогляд",
    loginOrRegistration: "Вхід/Реєстрація",
    loginToYourAccount: "Увійдіть в особистий кабінет",
    logIn: "Увійти",
    promotions: "Акції",
    promotionalProducts: "Товари акції",
    brands: "Бренди",
    searchDrug: "Пошук препарату",
    searchByBrand: "Пошук за брендом",
    searchByActiveIngredient: "Пошук за діючою речовиною",
    insuranceCovid: "Страховка від COVID-19",
    searchDrugsByActiveIngredient: "Пошук ліків за діючою речовиною",
    selectionDrugsByActiveIngredientOnline: "Підбір препаратів за діючою речовиною онлайн",
    drugstores: "Аптеки",
    partners: "Партнери",
    ourPartners: "Наші партнери",
    ourTeam: "Наша команда",
    deliveryAndPayment: "Доставка та оплата",
    qualityAssurance: "Гарантії якості",
    returnConditions: "Умови повернення",
    whatMakesUsDifferent: "Чим ми відрізняємося",
    aboutUs: "Про нас",
    blog: "Блог",
    covid: "Covid-19",
    bonusesByReviews: "Бонуси за відгуки",
    notField: "Не вказано",
    hideText: "Приховати текст",
    readMore: "Читати далі",
    readAnother: "Читати ще",
    readAll: "Читати все",
    readAllAnswers: "Читати всі відповіді",
    readCompletely: "Читати повністю",
    readArticle: "Читати статтю",
    save: "Зберегти",
    cancel: "Відміна",
    edit: "Редагувати",
    toAnswer: "Відповісти",
    name: "Ім'я",
    lastName: "Прізвище",
    middleName: "По батькові",
    birthday: "Дата народження",
    gender: "Стать",
    communicationLanguage: "Мова спілкування з apteka24.ua",
    about: "Про себе",
    ru: "Російська",
    uk: "Українська",
    male: "Чоловіча",
    female: "Жіноча",
    profilePhoto: "Фото профілю",
    change: "Змінити",
    show: {
        default: "Показати",
        more: "Показати ще",
        all: "Показати все",
        less: "Приховати"
    },
    informationAboutProduct: "Інформація про товар",
    informationAboutOrder: "Інформація про замовлення",
    orderPrice: "Сума замовлення",
    sendOrder: "Відправити замовлення",
    deliveryPrice: "Сума доставки",
    quantity: "Кількість",
    from: "Від",
    amount: "Сума",
    forAmount: "На суму",
    payment: "Оплата",
    total: "Разом",
    checkout: "Оформити замовлення",
    findDrugs: "Знайти ліки",
    learnMore: "Дізнатись більше",
    send: "Відправити",
    moreDetails: "Детальніше",
    moreDetailsAboutBonuses: "Докладніше про бонуси",
    sort: "Сортувати",
    reset: "Скинути",
    clear: "Очистити",
    clearList: "Очистити список",
    yourName: "Ваше ім'я",
    yourEmail: "Ваш e-mail",
    yourPhone: "Ваш телефон",
    yourMessage: "Ваше повідомлення",
    yourComment: "Ваш коментар",
    frequentlyAskedQuestions: "Поширені запитання",
    didWeAnswerYourQuestion: "Ми відповіли на Ваші питання?",
    ifNotLetUsKnow: "Якщо ні, будь ласка, дайте нам знати",
    notifyOfRepliesByEmail: "Повідомляти про відповіді по електронній пошті",
    cities: "Міста",
    pharmaciesForIssue: "Аптеки для видачі",
    drugsDelivered: "Ліків доставлено",
    customers: "Покупці",
    howWeWork: "Як ми працюємо",
    doctorsAboutProject: "Лікарі про проект",
    recommend: "Рекомендовані",
    recommendedForPurchase: "Рекомендуємо до покупки",
    continueShopping: "Продовжити покупки",
    ascendingPrice: "За зростанням ціни",
    descendingPrice: "За зменшенням ціни",
    youChoose: "Ви обрали",
    warning: "Увага",
    vendorCard: {
        contacts: {
            mainOffice: "Головний офіс",
            phone: "Телефон",
            email: "e-mail",
            fax: "Факс",
            site: "Сайт"
        },
        aboutCompany: "Про компанію ",
        johnson: {
            name: "ТОВ «Джонсон і Джонсон Україна»"
        },
        farkos: {
            name: "Фармацевтична компанія «ФарКоС»"
        }
    },
    buyInOneClick: "Купити в один клік",
    buy: "Купити",
    alreadyBought: "Вже купив(ла)",
    inBasket: "В кошику",
    basket: "Кошик",
    toBasket: "Перейти в кошик",
    toBuyer: "Покупцеві",
    company: "Компанія",
    companyRepresentative: "Представник компанії",
    officialRepresentativeOfApteka24: "Офіційний представник Аптека24",
    toPartners: "Партнерам",
    socialNetworks: "Соціальні мережі",
    massMediaAboutUs: "ЗМІ про нас",
    doctorsAboutTheService: "Лікарі про сервіс",
    vitaminsAndMinerals: "Вітаміни та мінерали",
    popularProducts: "Популярні товари",
    antibiotics: "Антибіотики",
    gynecologicalPreparations: "Гінекологічні препарати",
    urologicalPreparations: "Урологічні препарати",
    links: "Посилання",
    openOriginalImage: "Відкрити велике зображення",
    filter: "Фільтр",
    filters: "Фільтри",
    activeIngredient: "Активний інгредієнт",
    seller: "Продавець",
    sellerOfProduct: "Продавець товару",
    categories: "Категорії",
    allCategories: "Всі категорії",
    price: "Ціна",
    priceFor: "Ціна на",
    prices: "Ціни",
    emptySearchResult: "Нічого не знайдено, спробуйте змінити запит",
    youMeant: "Можливо, ви мали на увазі",
    selectedAll: "Вибрати все",
    select: "Виберіть",
    apply: "Застосувати",
    accept: "Прийняти",
    removeSelection: "Скинути вибір",
    delete: "Видалити",
    toHomePage: "Перейти на головну",
    informAboutAvailability: "Повідомити, коли з'явиться",
    willInformAboutAvailability: "Повідомимо про наявність",
    legitimnost: "Легітимність",
    ourMission: "Наша місія",
    ourAwards: "Наші нагороди",
    ourAdvantages: "Наші переваги",
    socialPrograms: "Соціальні програми",
    medicalAnswers: "Медичні відповіді",
    medicalExperts: "Медичні експерти",
    cooperationProposals: "Пропозиції про співпрацю",
    partnerAccount: "Особистий кабінет партнера",
    forPregnantAndBreastFeeders: "Вагітним та жінкам, які годують груддю",
    duringPregnancyAndBreastfeeding: "При вагітності та грудному вигодовуванні",
    howToOrderDrugs: "Як замовити ліки",
    editorialPolicy: "Редакційна політика",
    reviewsPostingPolicy: "Політика публікації відгуків",
    marketingPolicy: "Маркетингова політика",
    showMoreInstruction: "Переглянути всю інструкцію",
    showMoreDescription: "Переглянути весь опис",
    showMoreProperties: "Дивитися всі характеристики",
    showMoreHistory: "Дивитися всю історію",
    found: "Знайдено",
    popularCategories: "Популярні категорії",
    free: "Безкоштовно",
    deliveryCompany: "Транспортна компанія",
    orderUpTo: "Замовлення до",
    orderFrom: "Замовлення від",
    currency: {
        uah: "грн"
    },
    deliveryTo: "Доставка в",
    aboutDeliveryLocations: "Ми возимо замовлення в усі населені пункти України",
    enterCityNameOrVillage: "Вкажіть потрібне Вам місто або селище, щоб побачити доступні способи доставки",
    cashbackForPurchases: "Кешбек за покупки",
    discountPromoCodes: "Промокоди на знижки",
    giftCoupons: "Подарункові купони",
    referralProgram: "Реферальна програма",
    freeDelivery: "Безкоштовна доставка",
    drugBenefits: "Переваги препарату",
    privacyPolicy: "Політика конфіденційності",
    download: "Завантажити",
    cityNames: {
        kiev: "Київ",
        kharkov: "Харків",
        dnepr: "Дніпро",
        odessa: "Одеса",
        rovno: "Рівне",
        vinnitsa: "Вінниця",
        zaporozhe: "Запоріжжя",
        ivanoFrankovsk: "Івано-Франківськ",
        kramatorsk: "Краматорськ",
        kremenchug: "Кременчуг",
        krivoyRog: "Кривий Ріг",
        lvov: "Львів",
        nikolaev: "Миколаїв",
        poltava: "Полтава",
        sumy: "Суми",
        ternopol: "Тернопіль",
        kherson: "Херсон",
        cherkassy: "Черкаси",
        chernovtsy: "Чернівці",
        chernigov: "Чернігів"
    },
    createApplication: "Залишити заявку",
    validity: "Термін дії",
    filling: "Наповнення",
    conditions: "Умови",
    priceFrom: "Цiна вiд",
    priceTo: "Цiна до",
    workTime: "Графік роботи",
    supportService: "Служба підтримки",
    warranty: "Гарантія",
    code: "Код",
    productCode: "Код товару",
    genericDrug: "Препарат дженерик",
    thankYouForTheOrder: "Дякуємо за замовлення",
    thank: "Дякуємо",
    callYouToClarifyOrderDetails: "Ось-ось зателефонуємо Вам, щоб уточнити деталі",
    chooseYourCity: "Виберіть своє місто",
    vendor: "Виробник",
    countryOfManufacture: "Країна-виробник",
    doctorsAnswersYourQuestions: "Відповіді лікарів на Ваші питання",
    officialAnswer: "Офіційна відповідь",
    sources: "Джерела",
    similarQuestions: "Подібні запитання",
    amountInTheCatalog: "{0} шт. у каталозі",
    amountOfThingsYouNeedToKnow: "{0} речей, які вам потрібно знати",
    amountOfBonusMoney: "{0} бонусних гривень",
    recommendations: "Рекомендації",
    editorialStaff: "Редакція",
    censor: "Цензор",
    updated: "Оновлено",
    created: "Створено",
    verified: "Перевірено",
    yourDataIsBeingVerified: "Ваші дані на перевірці",
    home: "Головна",
    notAvailable: "Немає в наявності",
    setRate: "Поставте оцінку",
    allSearchResults: "Всі результати пошуку",
    searchHistory: "Історія пошуку",
    youMayBeLookingFor: "Можливо, Ви шукаєте",
    priceAndAvailabilityAreRelevantTo: "Ціна і наявність актуальні на",
    certificate: "Сертифікат",
    allArticles: "Всі статті",
    redaction: "Редакція",
    redactionFrom: "Редакція від",
    historyBonusTransactions: "Історія нарахування та списання бонусів",
    youDontHaveAnyBonusesYet: "У Вас поки немає бонусів",
    accumulateBonuses: "Накопичуйте бонусні гривні і використовуйте їх при оплаті своїх покупок",
    pricesFor: "Ціни на",
    cashback: "Кешбек",
    returnToBonusAccount: "Повернеться на бонусний рахунок",
    informed: "Ознайомлений",
    carefully: "З обережністю",
    lookAt: "Переглянути",
    address: "Адреса",
    searchByAddressOrDrugstoreName: "Пошук за адресою чи по назві мережі",
    drugstoresList: "Список аптек",
    yourCity: "Ваше місто",
    asList: "Списком",
    asMap: "На мапі",
    allCities: "Усі міста",
    showDrugstoresByCity: "Відобразити аптеки по населеному пункту",
    showMoreCities: "Ще {0} міст",
    severalDrugstores: "Декілька аптек",
    partnerDrugstores: "Партнерські аптеки",
    selfDeliveryPoint: "Пункт самовивозу",
    freeSelfDeliveryFromDrugstores: "Безкоштовний самовивіз з аптек",
    drugstoreAddress: "Адреса аптеки",
    howToGetThere: "Як дістатися",
    seeOnTheMap: "Дивитися на мапі",
    howPlaceOrderToDrugstore: "Як зробити замовлення у цю аптеку",
    findAllDrugsYouNeed: "Знайти усі необхідні препарати на нашому сайті",
    addToCartAndStartCheckout: "Додати їх у кошик та почати оформляти замовлення",
    chooseDrugstoreInDeliveryMethods: "Обрати цю аптеку у способах доставки",
    orYouCanPlaceAnOrderByPhone: "Або можна оформити замовлення за телефоном",
    codeCopied: "Код скопійований",
    toShopping: "За покупками",
    wantMoreBenefits: "Вау, хочу більше переваг",
    examplesOfTasks: "Приклади завдань",
    rightNowYouCan: "А ось прямо зараз Ви можете",
    registeredEmployees: "Зареєстровано співробітників",
    bonusesAccrued: "Бонусів нараховано",
    giftsLeft: "Залишилося подарунків",
    sendRequest: "Відправити запит",
    saving: "Економія",
    likes: "Лайки",
    watchChannel: "Дивитися канал",
    aboutDoctor: "Про лікаря",
    articles: "Статті",
    expert: "Експерт",
    registrationDate: "Дата реєстрації",
    expertInTopic: "Експерт в темі",
    certificates: "Сертифікати",
    receive: "Отримати",
    fine: "Добре",
    doctorsCertificate: "Сертифікат лікаря",
    addPhoto: "Додати фото",
    addPhotoDescription: "Додавайте до 10 зображень в форматах .jpg, .png, розміром файлу до 15 МБ",
    images: "Зображення",
    usersPhotos: "Фотографії користувачів",
    pcs: "Шт",
    detailedInformation: "Детальна інформація",
    content: "Зміст",
    usersPhoto: "Фотографії покупців",
    seeAllPhotos: "Подивитися всі зображення",
    goToGallery: "Перейти в галерею",
    topNegativeReview: "Кращий негативний відгук",
    topPositiveReview: "Кращий позитивний відгук",
    uploadPhoto: "Завантажити фотографії",
    done: "Готово",
    almostDone: "Майже готово",
    uii: "Уіі",
    letsStart: "Ну що, почнемо",
    changeName: "Змінити ім'я",
    showMore: "Показати ще"
};
